# Numpy Arrays

## Arrays

In [3]:
import numpy as np

In [4]:
mylist = [1, 2, 3]

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
nestedlist = [[1, 2], [3, 4], [5, 6]]

In [7]:
nestedlist

[[1, 2], [3, 4], [5, 6]]

In [8]:
np.array(nestedlist)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Range

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

## Few Other Types Of Matrices

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.zeros((4, 4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Evenly Spaced Matrices

In [61]:
np.linspace(0, 11, num=10)

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [23]:
np.linspace(1, 10, num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random Numbers

In [29]:
np.random.rand(2)            ## random numbers from Uniform Distribution

array([0.68889901, 0.53309342])

In [30]:
np.random.rand(4, 4)

array([[0.34530902, 0.83134172, 0.36213796, 0.45167848],
       [0.96984752, 0.15711059, 0.67172894, 0.06532533],
       [0.58886672, 0.54104738, 0.12233517, 0.07377492],
       [0.80818278, 0.66930546, 0.49219969, 0.63848447]])

In [31]:
np.random.randn(4)         ## Random Numbers from Standard Normal Distribution

array([ 1.02806635,  1.97262097,  0.39576726, -0.27126986])

In [32]:
np.random.randn(4, 4)

array([[-1.26358081,  0.18038608, -1.51582484,  0.01130243],
       [ 1.05183199, -0.18391296, -0.18760131, -0.1641888 ],
       [ 1.82815153,  1.47051307, -1.90672207, -0.0863215 ],
       [ 1.03048916, -0.92620712,  1.33079554,  1.78299023]])

In [33]:
np.random.randint(4, 10)       ## Random Integers

6

In [34]:
np.random.randint(4, 100, size=10)

array([29, 81, 71,  5, 77,  9, 47, 87, 34, 86])

In [35]:
np.random.randint(4, 100, size=(2, 2))

array([[67, 45],
       [11, 94]])

## Seed

In [36]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [43]:
np.random.rand(4)

array([0.59241457, 0.04645041, 0.60754485, 0.17052412])

## Some Useful Methods

In [44]:
arr = np.arange(25)

In [46]:
ranarr = np.random.randint(0, 50, 10)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
ranarr

array([17,  3, 24, 13, 49,  8, 25,  1, 19, 27])

In [51]:
arr.shape

(25,)

In [50]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr  # not permenant

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr.max()

49

In [55]:
ranarr.argmax()

4

In [56]:
ranarr.min()

1

In [57]:
ranarr.argmin()

7

In [58]:
ranarr.dtype

dtype('int64')