# Numpy Index

## Indexing 1D Array

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0, 11)

In [11]:
slice_of_arr = arr[0:5]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [13]:
slice_of_arr[:] = 99

In [14]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [16]:
arr           ## it also changed Parent Array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr.copy()

In [18]:
slice_of_arr[:] = 100

In [20]:
slice_of_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## Indexing 2D arrays

In [22]:
arr2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [23]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr2d.shape

(3, 3)

In [25]:
arr2d[0]

array([ 5, 10, 15])

In [26]:
arr2d[-1]

array([35, 40, 45])

In [27]:
arr2d[1][1]

25

In [28]:
arr2d[1, 1]

25

In [29]:
arr2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [30]:
arr2d[:2, 1:]

array([[10, 15],
       [25, 30]])

## Conditional Selection

In [31]:
arr = np.arange(1, 11)

In [32]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [34]:
boolean_arr = arr > 4
arr[boolean_arr]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])